### ISSUE TITLE
GitHub Sponsors

### ISSUE THREAD

**Issue by jirenius** [jirenius/go-res#56]
## Issue

GitHub funding support should be added to the project.

## Notes

Done by adding the file `.github/FUNDING.yml` with the content:
```yml
# These are supported funding model platforms
github: [jirenius]
custom: ["https://www.paypal.me/jirenius"]
```
